name: .NET 5 + Testes + Docker + Azure Container Registry + Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      CAMINHO_PROJETO_TESTES: ./APITemperatura.Especificacoes/APITemperatura.Especificacoes.csproj
      CAMINHO_PROJETO_WEBAPP: ./APITemperatura
      NOME_IMAGEM: apitemperaturadevweek0
      NOME_COMPLETO_IMAGEM: ${{ secrets.CONTAINER_REGISTRY }}/$NOME_IMAGEM
      NOME_WEBAPP: apitemperaturadevweek0

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100

    - name: Executar testes automatizados
      run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal

    - name: Login no Azure Container Registry
      uses: docker/login-action@v1.6.0
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    - name: Build e Push no Azure Container Registry
      run: |
        cd ${{ env.CAMINHO_PROJETO_WEBAPP }}
        docker build . --file Dockerfile --tag ${{ env.NOME_COMPLETO_IMAGEM }}:latest
        docker tag ${{ env.NOME_COMPLETO_IMAGEM }}:latest ${{ env.NOME_COMPLETO_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker push ${{ env.NOME_COMPLETO_IMAGEM }}
    - name: Azure Login - Conectando com Credenciais no Azure
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure WebApp - Deployment da Aplicacao - Containers
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.NOME_WEBAPP }}
        images: 'groffegithubactions.azurecr.io/apitemperaturadevweek0:${{ github.run_number }}'
